#define LTP_FRAME_SIZE 6
#define LTP_CMD_ADVERTISE 0x01
#define LTP_DATA_NOP 0x00
#define LTP_CMD_DETECTION 0x21
#define LTP_CMD_CALIBRATE 0x10
#define LTP_CMD_RAZ_FREQ 0x40
#define LTP_CMD_ADD_FREQ 0x30


